package nanithing.services;

import nanithing.model.Game;

/**
 * Game-related services.
 */
public interface GameService {
	/**
	 * Retrieve a game by id.
	 *
	 * @param id The id of the game
	 * @return The game with the given id
	 */
	Game findById(String id);

	/**
	 * Create a game to the OPEN state.
	 *
	 * @param game The game characteristics; id can be null, in which case it will be autogenerated; the created game will always be in the {@code OPEN} state
	 * @return
	 */
	Game create(Game game);
}
